### ISSUE TITLE
Domanda da neofita

### ISSUE THREAD

**Issue by dapuzz** [mansellrace/Esphome-Samsung-Climate#1]
Ciao @mansellrace, come mai non hai usato i 5v e il ground del sensore IR ma hai cercato altri pin in giro sulla scheda?
Dici che non funzionerebbe oppure è preferibile non interferire con il sensore?

Grazie!

**Comment by mansellrace** [comment]
Il sensore era alimentato attraverso una resistenza sul positivo quindi ho preferito prendere alimentazione a monte
